### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by boedy**
Illuminate\Events not included in composer. This caused me confusion when installing the module.

### CODE REVIEW

**Comment by franzliedke** [comment]
This is a read-only subtree split of the [laravel/framework repository](https://github.com/laravel/framework). Please close this and re-open over there.

**Comment by GrahamCampbell** [comment]
> Illuminate\Events not included in composer. This caused me confusion when installing the module.

Do you ever read the suggested packages composer gives you? This is not confusing, and this pull request will not be accepted on either repository. Sorry. Please close this.

**Comment by boedy** [comment]
Well for me it was confusing. I ran composer update which updated the package from 4.2.12 to 5.0.0 which broke my application because the illuminate/events package was removed by the update.

I've read the suggested packages when I ran into the error and illuminate/events is not in there. So maybe add that then? I'll close this PR.

**Comment by GrahamCampbell** [comment]
> I've read the suggested packages when I ran into the error and illuminate/events is not in there. So maybe add that then? I'll close this PR.

It is in there. I added it myself.

**Comment by boedy** [comment]
I'm sorry, I might be blind, but where to be exact? Is it required by an other package?

**Comment by GrahamCampbell** [comment]
It wasn't actually into 5.0.0 - we forgot about it, but it was added in a later 5.0.x tag. Sorry if we caused any confusion, but it is currently documented for people upgrading, even though we missed it for the earlier upgraders,

**Pull request closed without merging**
