### PR TITLE
No mention of the reason/benefits to keep query log in memory by default.

### PR DESCRIPTION
**Pull request by frombunin**
http://laravel.com/docs/4.2/database#query-logging

In case of big data migrations/conversions it leads to a lack of memory.

### CODE REVIEW

**Comment by franzliedke** [comment]
Wrong repo, please close this and send it to https://github.com/laravel/framework instead.

Also, something seems to have gone wrong with your PR.

**Comment by GrahamCampbell** [comment]
I think this was he trying to create an issue. Issues are disabled on this repo. We don't want them reporting here,

**Comment by frombunin** [comment]
Yeap, that was an issue. Ok, I will try post it to mention repo.

**Comment by GrahamCampbell** [comment]
Please close this. 4.2 isn't supported anyway.

**Pull request closed without merging**
