### PR TITLE
Added auto-increment TINYINT

### PR DESCRIPTION
**Pull request by lguima**
There was an option to make auto-increment for all Integers types, except for TINYINT.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This was already rejected because it has no use case.

**Comment by GrahamCampbell** [comment]
Also, never send PRs to this repo anyway. ALL must be directed to laravel/framework as this repo is clearly marked as read only.

**Comment by lguima** [comment]
Thanks for answer and I'm sorry about the repo.

**Comment by GrahamCampbell** [comment]
No problem, please close this though. :)

**Comment by lguima** [comment]
Sure!

**Comment by shehi** [comment]
@lguima : No point sending this PR, I contributed all incrementals to the repo, @taylorotwell for some reason didn't like having auto-increments for TINYINT.

**Comment by GrahamCampbell** [comment]
@shehi As I said:

> This was already rejected because it has no use case.

**Pull request closed without merging**
