### PR TITLE
0 should also be treated as timestamp

### PR DESCRIPTION
**Pull request by gdxhsw**
Hi I found there is a bug while model get a 0 timestamp.

This bug is fixed in 5.0 but not fix in 4.2 yet.

Thanks.

### CODE REVIEW

**Comment by franzliedke** [comment]
Please close this and send it to the laravel/framework repository instead. This is a read-only repo.

**Comment by GrahamCampbell** [comment]
Actually, please just close this and don't send another PR. We're not fixing this on 4.2.

**Comment by gdxhsw** [comment]
Does that mean you will not maintain 4.2 ?

**Comment by GrahamCampbell** [comment]
Yes, only 5.1 is maintained. Please close this.

**Pull request closed without merging**
